const fs = require('fs');
const os = require('os');
const path = require('path');
const { loadConfig, normalizeBaseUrl, AUTH_FILE } = require('./config');
const profileMod = require('./profile');
const { buildClient, ApiError } = require('./api');
const { parseArgs } = require('./args');

const VERSION = require('../package.json').version;

// Build info is generated by scripts/build-info.js at build time. Falls back
// to "(dev)" when running from source without having built once.
let _buildInfo = { sha: '', date: '' };
try { _buildInfo = require('./build-info'); } catch {}
const BUILD = _buildInfo.sha
  ? (_buildInfo.date ? `${_buildInfo.sha} · ${_buildInfo.date}` : _buildInfo.sha)
  : '(dev)';

const ABOUT = `md_cli ${VERSION}  ·  build ${BUILD}
Command-line client for md-browse / MarkdownHub — list, search, upload,
update, version, share, and download markdown documents; manage folders,
tokens, and audit logs.`;

const HELP = `md_cli — command-line client for md-browse

Usage:
  md_cli <command> [options]

Document commands:
  list                       List documents
  search <query>             Full-text search
  get <id>                   Fetch a document (raw markdown by default)
  upload <file>              Upload a .md file
  update <id>                Update a document's metadata or content
  delete <id>                Soft-delete a document
  versions <id>              List version history
  rollback <id>              Roll back to a prior version (requires --version)
  chunks <id>                Show RAG-style chunks for a document
  download <id>              Download a single document
  download-batch <ids>       Download many docs as a zip (comma-separated ids)
  batch-delete <ids>         Soft-delete many docs at once
  batch-move <ids>           Move many docs to a folder (--folder <id|root>)

Sharing:
  share <subcommand>         create / list / delete / open

Folder commands:
  folders [list]             List folders
  folders create <name>      Create a folder (--parent <id>)
  folders rename <id> <name> Rename a folder
  folders move <id>          Move a folder (--parent <id|root>)
  folders rm <id>            Delete a folder (docs are moved to parent)

Catalog:
  categories                 List distinct categories
  tags                       List distinct tags

Token management (server-side):
  tokens list                List your agent tokens
  tokens revoke <id|prefix>  Revoke an agent token by id or token_prefix

Audit:
  audit                      Show audit log (--actor-type, --action, --page-size)

Assets:
  assets list <doc-id>       List asset files for a document
  assets upload <doc-id> <files...>
                             Upload one or more asset files to a document
  folder-assets list <folder-id>
                             List asset files for a folder
  folder-assets upload <folder-id> <files...>
                             Upload assets to a folder
  folder-assets rm <folder-id> <filename>
                             Delete a folder asset

Admin (requires admin role; uses your session JWT — pass --username/--password
or rely on saved profile credentials):
  admin users list           List all users
  admin users add <name>     Create a user (--password, --role)
  admin users update <name>  Update role/password
  admin users rm <name>      Delete a user
  admin settings get         Show server settings
  admin settings set         Update server settings (--registration on|off)

Auth & profiles:
  login                      Log in (username/password) and mint a CLI token
  logout                     Remove the active profile (or --all / --profile)
  use <profile>              Switch the active profile
  profiles [list|rm|rename]  Manage saved profiles (~/.md-browse/profiles)
  whoami                     Show active profile, token source, and identity

Other:
  health / ping              Probe /api/health
  help [command]             Show help for a command
  version                    Print CLI version

Global options:
  --env-file <path>          Load env from a specific file (default: walk up from cwd)
  --token <t>                Override MD_BROWSE_TOKEN for this call
  --url <baseurl>            Override MD_BROWSE_URL (e.g. https://md.example.com)
  --profile <name>           Use a specific saved profile for this call
  --json                     Print raw JSON output where applicable
  -h, --help                 Show help

Profiles live in ~/.md-browse/profiles/. Token resolution priority
(highest first): --token  >  MD_BROWSE_TOKEN env  >  .env MD_BROWSE_TOKEN  >
--profile NAME  >  MD_BROWSE_PROFILE env  >  active profile (~/.md-browse/current).

Configuration via .env (in cwd or any parent directory):
  MD_BROWSE_TOKEN=agt_...    Optional. Overrides any saved profile token.
  MD_BROWSE_URL=https://...  Optional. Overrides any saved profile URL.
  MD_BROWSE_PROFILE=name     Optional. Selects a saved profile by name.

Run \`md_cli help <command>\` for detailed usage.
`;

const COMMAND_HELP = {
  list: `md_cli list [options]

Options:
  --tag <tag>            Filter by tag
  --project <name>       Filter by project
  --folder <id>          Filter by folder id (or 'root')
  --q <query>            Free-text filter on title/description/tags
  --page <n>             Page number (default 1)
  --page-size <n>        Items per page (default 20, max 100)
  --sort-by <field>      updated_at | created_at | title (default updated_at)
  --sort-order <dir>     asc | desc (default desc)
  --json                 Print full JSON response
`,
  search: `md_cli search <query> [options]

Options:
  --page <n>             Page number
  --page-size <n>        Items per page
  --json                 Print full JSON response
`,
  get: `md_cli get <id> [options]

Options:
  -o, --output <file>    Write content to file instead of stdout
  --rendered             Print rendered HTML (default: raw markdown)
  --json                 Print full document metadata JSON
`,
  upload: `md_cli upload <file> [options]

Options:
  --folder <id>          Folder id to place the doc in
  --tags a,b,c           Comma-separated tags
  --description <text>   Document description
  --category <name>      Document category
  --project <name>       Project name
  --visibility <level>   public | team | private
  --json                 Print full JSON response

Token must include scope documents:write.
`,
  update: `md_cli update <id> [options]

At least one of:
  --title <text>             Set title
  --description <text>       Set description
  --content-file <path>      Replace content from file
  --content <text>           Replace content inline (small bodies)
  --change-note <text>       Note attached to the new version (when content changes)
  --tags a,b,c               Replace tags
  --category <name>          Set category
  --project <name>           Set project
  --visibility <level>       public | team | private
  --folder <id>              Move to folder

Token must include scope documents:write.
`,
  delete: `md_cli delete <id>

Soft-deletes the document. Token must include scope documents:write.
`,
  versions: `md_cli versions <id> [--json]

Lists version history (newest first).
`,
  rollback: `md_cli rollback <id> --version <n> [--note <text>]

Rolls back to the given version, creating a new version on top.
Token must include scope documents:write.
`,
  chunks: `md_cli chunks <id> [options]

Options:
  --size <n>             Target chunk size (chars; server default ~1500)
  --overlap <n>          Overlap between chunks (chars)
  --json                 Print full JSON response
`,
  download: `md_cli download <id> [options]

Options:
  -o, --output <file>    Output filename (default: derived from doc title)
`,
  'download-batch': `md_cli download-batch <id1,id2,id3> [options]

Options:
  -o, --output <file>    Output zip path (default: documents.zip)
`,
  'batch-delete': `md_cli batch-delete <id1,id2,id3> [--yes]

Soft-deletes the listed documents in one request. Pass --yes (or -y) to
skip the confirmation prompt.
`,
  'batch-move': `md_cli batch-move <id1,id2,id3> --folder <id|root>

Moves the listed documents to the given folder. Use 'root' to move to the
top level (folder_id=null).
`,
  share: `md_cli share <subcommand>

Subcommands:
  create <doc-id> [--code <access-code>]   Create a public share link
  list [doc-id]                            List share links — for one doc, or all of yours
  delete <share-id>                        Revoke a share link
  open <token> [--code <access-code>]      Fetch a shared doc (no auth needed)

Notes:
  - The printed share URL is derived from MD_BROWSE_URL.
    Override with --site-url <https://md.example.com> if you need a different one.
  - 'create' and 'delete' need scope documents:write; 'list' needs documents:read.
  - 'open' makes a public, unauthenticated call — no MD_BROWSE_TOKEN required.
`,
  folders: `md_cli folders <subcommand>

Subcommands:
  list                              (default) List all folders
  create <name> [--parent <id>]     Create a folder
  rename <id> <new-name>            Rename a folder
  move <id> --parent <id|root>      Move a folder
  rm <id>                           Delete a folder (its docs move to parent)
`,
  categories: `md_cli categories [--json]

Lists distinct document categories. No auth required.
`,
  tags: `md_cli tags [--json]

Lists distinct document tags. No auth required.
`,
  tokens: `md_cli tokens <subcommand>

Subcommands:
  list                       List your agent tokens (id, name, scopes, last_used)
  revoke <id|prefix>         Revoke an agent token by its UUID id or 8-char prefix
`,
  audit: `md_cli audit [options]

Options:
  --actor-type <type>    Filter by actor_type (user | agent)
  --action <name>        Filter by action (e.g. document.update)
  --page <n>             Page number
  --page-size <n>        Page size (max 100)
  --json                 Print full JSON response
`,
  assets: `md_cli assets <subcommand>

Subcommands:
  list <doc-id>                          List asset files attached to a document
  upload <doc-id> <file> [<file>...]     Upload one or more assets to a document
`,
  'folder-assets': `md_cli folder-assets <subcommand>

Subcommands:
  list <folder-id>                       List folder asset files
  upload <folder-id> <file> [<file>...]  Upload assets to a folder
  rm <folder-id> <filename>              Delete a folder asset
`,
  admin: `md_cli admin <subcommand>

Subcommands:
  users list                                List all users
  users add <name> [--password <pw>] [--role admin|editor|viewer]
                                            Create a user
  users update <name> [--password <pw>] [--role admin|editor|viewer]
                                            Update a user
  users rm <name>                           Delete a user
  settings get                              Show server settings
  settings set [--registration on|off]      Update server settings

Admin commands need a session JWT, not your CLI agent token. They re-auth
using the saved profile's stored username/password, or you can pass:
  --username <name> --password <pw>         Use these instead
`,
  whoami: `md_cli whoami [--json]

Prints the active profile, the profile actually in use for this call,
the configured base URL, env file path, token source, and the list of
all saved profiles.
`,
  login: `md_cli login [options]

Logs in with your md-browse username/password and saves a CLI token to a
profile file (~/.md-browse/profiles/<name>.json, mode 0600). The new profile
becomes active by default.

Options:
  --username <name>      Login username (otherwise prompted)
  --password <pw>        Login password (otherwise prompted, hidden)
  --url <baseurl>        Base URL (defaults to MD_BROWSE_URL or current profile).
                         Accepts http(s)://host or http(s)://host/api —
                         the /api suffix is normalized.
  --profile <name>       Profile name (default: derived from URL hostname,
                         e.g. https://md.example.com → "md")
  --no-switch            Don't switch the active profile to this one
  --force                Overwrite an existing auto-derived profile name
                         (explicit --profile NAME always overwrites)
  --name <text>          Display name for the minted token (default:
                         "md_cli@<hostname> YYYY-MM-DD HH:MM")
  --scopes a,b,c         Comma-separated scopes (default: all standard).
                         Valid: documents:read, documents:write,
                         versions:read, search:read, audit:read
  --save-password        Also store username/password in the profile so admin
                         commands can re-auth without prompting (mode 0600)

Already have an agent token? Skip the username/password flow:
  --token <agt_…>        Save this token directly (validated against
                         /v1/documents unless --no-validate is given)
  --no-validate          Skip the validation request when using --token

Token resolution priority (highest first):
  1. --token flag (on any command)
  2. MD_BROWSE_TOKEN env var
  3. .env file (cwd or any parent)
  4. --profile NAME flag (loads profiles/NAME.json)
  5. MD_BROWSE_PROFILE env var
  6. active profile (~/.md-browse/current)
`,
  logout: `md_cli logout [options]

Removes the active profile file and clears ~/.md-browse/current.
If other profiles still exist, the first remaining one becomes active so
you don't end up with no default.

Options:
  --profile <name>       Log out of a specific profile instead of the active one
  --all                  Remove every profile (and the current pointer)
`,
  use: `md_cli use <profile>

Switches the active profile (writes ~/.md-browse/current). All later
commands without an explicit --profile / --url use this one.
Run \`md_cli profiles\` to see the available names.
`,
  profiles: `md_cli profiles [subcommand]

Subcommands:
  list                       (default) List all saved profiles
  rm <name>                  Delete a profile (clears active if it was active)
  rename <old> <new>         Rename a profile (updates active if needed)
`,
  health: `md_cli health [--json]

Probes /api/health. No auth required.
`
};

function printJson(obj) { process.stdout.write(JSON.stringify(obj, null, 2) + '\n'); }
function out(s) { process.stdout.write(s + '\n'); }
function err(s) { process.stderr.write(s + '\n'); }

function buildContext(flags) {
  const cfg = loadConfig({
    envFile: flags['env-file'],
    profile: flags.profile
  });
  if (flags.token) {
    cfg.token = flags.token;
    cfg.tokenSource = 'flag';
  }
  if (flags.url) cfg.baseUrl = normalizeBaseUrl(flags.url);
  return { cfg, api: buildClient(cfg) };
}

// ── Prompts ──────────────────────────────────────────────────────────────────

function promptLine(question) {
  return new Promise((resolve, reject) => {
    process.stdout.write(question);
    const stdin = process.stdin;
    if (!stdin.isTTY) {
      let buf = '';
      stdin.on('data', (chunk) => { buf += chunk.toString(); });
      stdin.on('end', () => resolve((buf.split(/\r?\n/)[0] || '')));
      stdin.on('error', reject);
      return;
    }
    stdin.resume();
    let buf = '';
    const onData = (data) => {
      const s = data.toString('utf8');
      const nl = s.indexOf('\n');
      if (nl >= 0) {
        buf += s.slice(0, nl).replace(/\r$/, '');
        stdin.pause();
        stdin.removeListener('data', onData);
        resolve(buf);
        return;
      }
      buf += s;
    };
    stdin.on('data', onData);
  });
}

function promptHidden(question) {
  return new Promise((resolve, reject) => {
    process.stdout.write(question);
    const stdin = process.stdin;
    if (!stdin.isTTY) {
      let buf = '';
      stdin.on('data', (chunk) => { buf += chunk.toString(); });
      stdin.on('end', () => resolve(buf.replace(/[\r\n]+$/, '')));
      stdin.on('error', reject);
      return;
    }
    stdin.setRawMode(true);
    stdin.resume();
    let buf = '';
    const onData = (data) => {
      const s = data.toString('utf8');
      for (const ch of s) {
        const code = ch.charCodeAt(0);
        if (ch === '\n' || ch === '\r') {
          stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener('data', onData);
          process.stdout.write('\n');
          resolve(buf);
          return;
        }
        if (code === 3) {
          stdin.setRawMode(false);
          stdin.pause();
          process.stdout.write('\n');
          reject(new Error('aborted'));
          return;
        }
        if (code === 8 || code === 127) buf = buf.slice(0, -1);
        else buf += ch;
      }
    };
    stdin.on('data', onData);
  });
}

// ── Document commands ────────────────────────────────────────────────────────

async function cmdList(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { api } = buildContext(f);
  const res = await api.listDocuments({
    tag: f.tag,
    project: f.project,
    folder_id: f.folder,
    q: f.q,
    page: f.page,
    page_size: f['page-size'],
    sort_by: f['sort-by'],
    sort_order: f['sort-order']
  });
  if (f.json) return printJson(res);
  const { data = [], pagination } = res;
  if (!data.length) { out('(no documents)'); return; }
  for (const d of data) {
    const tags = (d.tags || []).join(',');
    out(`${d.id}  ${d.title || '(untitled)'}${tags ? `  [${tags}]` : ''}  v${d.latest_version}  ${d.updated_at || ''}`);
  }
  if (pagination) out(`\n— page ${pagination.page}/${Math.max(1, Math.ceil(pagination.total / pagination.page_size))} (${pagination.total} total) —`);
}

async function cmdSearch(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const q = f._[0];
  if (!q) throw new Error('search requires a query: md_cli search <query>');
  const { api } = buildContext(f);
  const res = await api.searchDocuments(q, { page: f.page, page_size: f['page-size'] });
  if (f.json) return printJson(res);
  const { data = [], pagination } = res;
  if (!data.length) { out('(no matches)'); return; }
  for (const d of data) {
    out(`${d.id}  ${d.title || '(untitled)'}`);
    if (d.snippet) out(`    ${d.snippet}`);
  }
  if (pagination) out(`\n— ${pagination.total} match${pagination.total === 1 ? '' : 'es'} —`);
}

async function cmdGet(rest) {
  const f = parseArgs(rest, { boolFlags: ['json', 'rendered'], aliases: { o: 'output' } });
  const id = f._[0];
  if (!id) throw new Error('get requires a document id: md_cli get <id>');
  const { api } = buildContext(f);
  const res = await api.getDocument(id, {
    include_raw: f.rendered ? undefined : 'true',
    include_rendered: f.rendered ? 'true' : undefined
  });
  if (f.json) return printJson(res);
  const body = f.rendered ? (res.content_html || '') : (res.content_md || '');
  if (f.output) {
    fs.writeFileSync(path.resolve(f.output), body);
    out(`wrote ${body.length} bytes to ${f.output}`);
  } else {
    process.stdout.write(body);
    if (!body.endsWith('\n')) process.stdout.write('\n');
  }
}

async function cmdUpload(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const file = f._[0];
  if (!file) throw new Error('upload requires a file path: md_cli upload <file>');
  if (!fs.existsSync(file)) throw new Error(`file not found: ${file}`);
  const { api } = buildContext(f);
  const res = await api.uploadDocument(file, {
    folder_id: f.folder,
    tags: f.tags,
    description: f.description,
    category: f.category,
    project: f.project,
    visibility: f.visibility
  });
  if (f.json) return printJson(res);
  const doc = (res.documents && res.documents[0]) || res;
  out(`uploaded ${doc.id}  ${doc.title || ''}`);
}

async function cmdUpdate(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const id = f._[0];
  if (!id) throw new Error('update requires an id: md_cli update <id>');
  const body = {};
  if (f.title !== undefined) body.title = f.title;
  if (f.description !== undefined) body.description = f.description;
  if (f.category !== undefined) body.category = f.category;
  if (f.project !== undefined) body.project = f.project;
  if (f.visibility !== undefined) body.visibility = f.visibility;
  if (f.folder !== undefined) body.folder_id = f.folder;
  if (f.tags !== undefined) body.tags = String(f.tags).split(',').map(s => s.trim()).filter(Boolean);
  if (f['change-note'] !== undefined) body.change_note = f['change-note'];
  if (f['content-file']) body.content_md = fs.readFileSync(path.resolve(f['content-file']), 'utf8');
  else if (f.content !== undefined) body.content_md = f.content;
  if (Object.keys(body).length === 0) throw new Error('update needs at least one field; see `md_cli help update`');

  const { api } = buildContext(f);
  const res = await api.updateDocument(id, body);
  if (f.json) return printJson(res);
  out(`updated ${res.id}  v${res.latest_version}`);
}

async function cmdDelete(rest) {
  const f = parseArgs(rest, { boolFlags: ['yes', 'json'], aliases: { y: 'yes' } });
  const id = f._[0];
  if (!id) throw new Error('delete requires an id: md_cli delete <id>');
  if (!f.yes && process.stdin.isTTY) {
    const ok = (await promptLine(`Delete ${id}? (y/N) `)).trim().toLowerCase();
    if (ok !== 'y' && ok !== 'yes') { out('aborted'); return; }
  }
  const { api } = buildContext(f);
  await api.deleteDocument(id);
  out(`deleted ${id}`);
}

async function cmdVersions(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const id = f._[0];
  if (!id) throw new Error('versions requires an id: md_cli versions <id>');
  const { api } = buildContext(f);
  const res = await api.listVersions(id);
  if (f.json) return printJson(res);
  const versions = (res.versions || []).slice().sort((a, b) => b.version_number - a.version_number);
  if (!versions.length) { out('(no versions)'); return; }
  for (const v of versions) {
    out(`v${v.version_number}  ${v.created_at}  ${v.created_by || ''}  ${v.change_note || ''}`);
  }
}

async function cmdRollback(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const id = f._[0];
  if (!id) throw new Error('rollback requires an id: md_cli rollback <id> --version <n>');
  const target = parseInt(f.version, 10);
  if (!target) throw new Error('rollback requires --version <n>');
  const { api } = buildContext(f);
  const res = await api.rollbackDocument(id, target, f.note);
  if (f.json) return printJson(res);
  out(`rolled back ${id} to v${target} (now v${res.latest_version})`);
}

async function cmdChunks(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const id = f._[0];
  if (!id) throw new Error('chunks requires a doc id: md_cli chunks <id>');
  const { api } = buildContext(f);
  const res = await api.getChunks(id, { size: f.size, overlap: f.overlap });
  if (f.json) return printJson(res);
  const chunks = res.chunks || res.data || [];
  if (!chunks.length) { out('(no chunks)'); return; }
  for (const c of chunks) {
    const head = `#${c.index ?? '?'}  ${c.token_count ? `~${c.token_count}tok` : ''}`;
    out(head);
    out((c.text || '').replace(/^/gm, '    '));
    out('');
  }
}

async function cmdDownload(rest) {
  const f = parseArgs(rest, { aliases: { o: 'output' } });
  const id = f._[0];
  if (!id) throw new Error('download requires an id: md_cli download <id>');
  const { api } = buildContext(f);
  const { buffer, filename } = await api.downloadDocument(id);
  const outPath = path.resolve(f.output || filename || `${id}.md`);
  fs.writeFileSync(outPath, buffer);
  out(`wrote ${buffer.length} bytes to ${outPath}`);
}

async function cmdDownloadBatch(rest) {
  const f = parseArgs(rest, { aliases: { o: 'output' } });
  const idsArg = f._[0];
  if (!idsArg) throw new Error('download-batch requires comma-separated ids: md_cli download-batch <id1,id2,...>');
  const ids = idsArg.split(',').map(s => s.trim()).filter(Boolean);
  if (!ids.length) throw new Error('no valid ids supplied');
  const { api } = buildContext(f);
  const { buffer } = await api.batchDownload(ids);
  const outPath = path.resolve(f.output || 'documents.zip');
  fs.writeFileSync(outPath, buffer);
  out(`wrote ${buffer.length} bytes to ${outPath} (${ids.length} document${ids.length === 1 ? '' : 's'})`);
}

async function cmdBatchDelete(rest) {
  const f = parseArgs(rest, { boolFlags: ['yes', 'json'], aliases: { y: 'yes' } });
  const idsArg = f._[0];
  if (!idsArg) throw new Error('batch-delete requires comma-separated ids');
  const ids = idsArg.split(',').map(s => s.trim()).filter(Boolean);
  if (!ids.length) throw new Error('no valid ids supplied');
  if (!f.yes && process.stdin.isTTY) {
    const ok = (await promptLine(`Delete ${ids.length} document${ids.length === 1 ? '' : 's'}? (y/N) `)).trim().toLowerCase();
    if (ok !== 'y' && ok !== 'yes') { out('aborted'); return; }
  }
  const { api } = buildContext(f);
  const res = await api.batchDelete(ids);
  if (f.json) return printJson(res);
  out(`deleted ${res.deleted?.length || 0} document${(res.deleted?.length || 0) === 1 ? '' : 's'}`);
}

async function cmdBatchMove(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const idsArg = f._[0];
  if (!idsArg) throw new Error('batch-move requires comma-separated ids');
  const ids = idsArg.split(',').map(s => s.trim()).filter(Boolean);
  if (!ids.length) throw new Error('no valid ids supplied');
  if (f.folder === undefined) throw new Error('batch-move requires --folder <id|root>');
  const folderId = (f.folder === 'root' || f.folder === '') ? null : f.folder;
  const { api } = buildContext(f);
  const res = await api.batchMove(ids, folderId);
  if (f.json) return printJson(res);
  out(`moved ${res.moved?.length || 0} document${(res.moved?.length || 0) === 1 ? '' : 's'} → ${folderId || 'root'}`);
}

// ── Sharing ──────────────────────────────────────────────────────────────────

function siteUrlFromBase(baseUrl, override) {
  if (override) return String(override).replace(/\/+$/, '');
  return baseUrl;
}

async function cmdShare(rest) {
  const sub = rest[0];
  if (!sub) throw new Error('share requires a subcommand: create | list | delete | open');
  const subRest = rest.slice(1);

  if (sub === 'create') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const docId = f._[0];
    if (!docId) throw new Error('share create requires a document id');
    const { cfg, api } = buildContext(f);
    const res = await api.createShare(docId, f.code);
    if (f.json) return printJson(res);
    const site = siteUrlFromBase(cfg.baseUrl, f['site-url']);
    out(`share id:  ${res.id}`);
    out(`token:     ${res.token}`);
    out(`url:       ${site}/share/${res.token}`);
    if (res.has_access_code) out(`note:      access code required to view`);
    return;
  }

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const docId = f._[0];
    const { cfg, api } = buildContext(f);
    let shares;
    if (docId) {
      shares = await api.listShares(docId);
    } else {
      const res = await api.listAllShares();
      shares = res.data || res;
    }
    if (f.json) return printJson(docId ? shares : { data: shares });
    if (!shares.length) {
      out(docId ? '(no share links for this document)' : '(no share links)');
      return;
    }
    const site = siteUrlFromBase(cfg.baseUrl, f['site-url']);
    for (const s of shares) {
      const lock = s.has_access_code ? ' 🔒' : '';
      const dead = s.document_deleted ? ' (doc deleted)' : '';
      const title = s.document_title ? `  "${s.document_title}"` : '';
      out(`${s.id}${title}${dead}`);
      out(`  url:     ${site}/share/${s.token}${lock}`);
      out(`  doc:     ${s.document_id || '?'}    created: ${s.created_at || '?'}`);
    }
    return;
  }

  if (sub === 'delete' || sub === 'rm' || sub === 'revoke') {
    const f = parseArgs(subRest);
    const shareId = f._[0];
    if (!shareId) throw new Error('share delete requires a share id');
    const { api } = buildContext(f);
    await api.deleteShare(shareId);
    out(`revoked share ${shareId}`);
    return;
  }

  if (sub === 'open') {
    const f = parseArgs(subRest, { boolFlags: ['json', 'rendered'], aliases: { o: 'output' } });
    const token = f._[0];
    if (!token) throw new Error('share open requires a share token');
    const { api } = buildContext(f);
    const res = await api.openShare(token, f.code);
    if (f.json) return printJson(res);
    const body = f.rendered ? (res.content_html || '') : (res.content_md || '');
    if (f.output) {
      fs.writeFileSync(path.resolve(f.output), body);
      out(`wrote ${body.length} bytes to ${f.output}`);
    } else {
      process.stdout.write(body);
      if (!body.endsWith('\n')) process.stdout.write('\n');
    }
    return;
  }

  throw new Error(`unknown share subcommand: ${sub}\nrun \`md_cli help share\` for usage.`);
}

// ── Folders ──────────────────────────────────────────────────────────────────

async function cmdFolders(rest) {
  const sub = rest[0] && !rest[0].startsWith('-') ? rest[0] : 'list';
  const subRest = (sub === rest[0]) ? rest.slice(1) : rest;

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const { api } = buildContext(f);
    const res = await api.listFolders();
    if (f.json) return printJson(res);
    if (!res.length) { out('(no folders)'); return; }
    const byId = Object.fromEntries(res.map(x => [x.id, x]));
    const childrenOf = {};
    for (const fld of res) {
      const k = fld.parent_id || '__root__';
      (childrenOf[k] ||= []).push(fld);
    }
    function walk(parentKey, depth) {
      const list = (childrenOf[parentKey] || []).slice().sort((a, b) => (a.name || '').localeCompare(b.name || ''));
      for (const fld of list) {
        out(`${'  '.repeat(depth)}- ${fld.name}  (${fld.id})`);
        walk(fld.id, depth + 1);
      }
    }
    walk('__root__', 0);
    return;
  }

  if (sub === 'create') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const name = f._[0];
    if (!name) throw new Error('folders create requires a name');
    const { api } = buildContext(f);
    const res = await api.createFolder(name, f.parent);
    if (f.json) return printJson(res);
    out(`created ${res.id}  ${res.name}`);
    return;
  }

  if (sub === 'rename') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const id = f._[0];
    const newName = f._[1];
    if (!id || !newName) throw new Error('folders rename requires <id> <new-name>');
    const { api } = buildContext(f);
    const res = await api.updateFolder(id, { name: newName });
    if (f.json) return printJson(res);
    out(`renamed ${id} → ${res.name}`);
    return;
  }

  if (sub === 'move') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const id = f._[0];
    if (!id) throw new Error('folders move requires <id>');
    if (f.parent === undefined) throw new Error('folders move requires --parent <id|root>');
    const parentId = (f.parent === 'root' || f.parent === '') ? null : f.parent;
    const { api } = buildContext(f);
    const res = await api.updateFolder(id, { parent_id: parentId });
    if (f.json) return printJson(res);
    out(`moved ${id} → parent ${parentId || 'root'}`);
    return;
  }

  if (sub === 'rm' || sub === 'delete') {
    const f = parseArgs(subRest, { boolFlags: ['yes'], aliases: { y: 'yes' } });
    const id = f._[0];
    if (!id) throw new Error('folders rm requires <id>');
    if (!f.yes && process.stdin.isTTY) {
      const ok = (await promptLine(`Delete folder ${id}? (y/N) `)).trim().toLowerCase();
      if (ok !== 'y' && ok !== 'yes') { out('aborted'); return; }
    }
    const { api } = buildContext(f);
    await api.deleteFolder(id);
    out(`deleted folder ${id}`);
    return;
  }

  throw new Error(`unknown folders subcommand: ${sub}\nrun \`md_cli help folders\` for usage.`);
}

// ── Tokens / Audit / Categories / Tags ───────────────────────────────────────

async function cmdTokens(rest) {
  const sub = rest[0];
  if (!sub) throw new Error('tokens requires a subcommand: list | revoke');
  const subRest = rest.slice(1);

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const { api } = buildContext(f);
    const res = await api.listAgentTokens();
    if (f.json) return printJson(res);
    const tokens = res.data || res || [];
    if (!tokens.length) { out('(no tokens)'); return; }
    for (const t of tokens) {
      out(`${t.id}  ${t.name || ''}`);
      out(`  prefix:    ${t.token_prefix || '?'}`);
      out(`  scopes:    ${(t.scopes || []).join(', ')}`);
      out(`  created:   ${t.created_at || ''}`);
      if (t.last_used_at) out(`  last used: ${t.last_used_at}`);
      if (t.expires_at) out(`  expires:   ${t.expires_at}`);
    }
    return;
  }

  if (sub === 'revoke' || sub === 'rm' || sub === 'delete') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const arg = f._[0];
    if (!arg) throw new Error('tokens revoke requires <id|prefix>');
    const { api } = buildContext(f);
    let id = arg;
    // If it's not a full UUID, try to resolve by token_prefix.
    if (!/^[0-9a-fA-F-]{36}$/.test(arg)) {
      const list = await api.listAgentTokens();
      const tokens = list.data || list || [];
      const match = tokens.find(t => (t.token_prefix || '').startsWith(arg) || (t.name || '') === arg);
      if (!match) throw new Error(`no token matching: ${arg}`);
      id = match.id;
    }
    await api.revokeAgentToken(id);
    out(`revoked ${id}`);
    return;
  }

  throw new Error(`unknown tokens subcommand: ${sub}`);
}

async function cmdAudit(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { api } = buildContext(f);
  const res = await api.listAuditLogs({
    actor_type: f['actor-type'],
    action: f.action,
    page: f.page,
    page_size: f['page-size']
  });
  if (f.json) return printJson(res);
  const { data = [], pagination } = res;
  if (!data.length) { out('(no audit entries)'); return; }
  for (const e of data) {
    out(`${e.created_at}  ${e.actor_type}:${e.actor_id}  ${e.action}  ${e.target_type || ''}/${e.target_id || ''}`);
    if (e.metadata && Object.keys(e.metadata).length) {
      out(`    ${JSON.stringify(e.metadata)}`);
    }
  }
  if (pagination) out(`\n— page ${pagination.page} (${pagination.total} total) —`);
}

async function cmdCategories(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { api } = buildContext(f);
  const res = await api.listCategories();
  if (f.json) return printJson(res);
  const list = Array.isArray(res) ? res : (res.data || []);
  if (!list.length) { out('(no categories)'); return; }
  for (const c of list) out(c);
}

async function cmdTags(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { api } = buildContext(f);
  const res = await api.listTags();
  if (f.json) return printJson(res);
  const list = Array.isArray(res) ? res : (res.data || []);
  if (!list.length) { out('(no tags)'); return; }
  for (const t of list) out(t);
}

async function cmdHealth(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { api } = buildContext(f);
  const res = await api.health();
  if (f.json) return printJson(res);
  out(`status:  ${res.status || 'unknown'}`);
  if (res.version) out(`version: ${res.version}`);
  if (res.uptime) out(`uptime:  ${res.uptime}`);
}

// ── Assets ───────────────────────────────────────────────────────────────────

async function cmdAssets(rest) {
  const sub = rest[0];
  if (!sub) throw new Error('assets requires a subcommand: list | upload');
  const subRest = rest.slice(1);

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const docId = f._[0];
    if (!docId) throw new Error('assets list requires <doc-id>');
    const { api } = buildContext(f);
    const res = await api.listDocumentAssets(docId);
    if (f.json) return printJson(res);
    const list = res.data || res.assets || res || [];
    if (!list.length) { out('(no assets)'); return; }
    for (const a of list) {
      const name = a.filename || a.name || a;
      const size = a.size ? `  ${a.size}B` : '';
      out(`${name}${size}`);
    }
    return;
  }

  if (sub === 'upload') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const docId = f._[0];
    const files = f._.slice(1);
    if (!docId || !files.length) throw new Error('assets upload requires <doc-id> <file> [<file>...]');
    for (const fp of files) {
      if (!fs.existsSync(fp)) throw new Error(`file not found: ${fp}`);
    }
    const { api } = buildContext(f);
    const res = await api.uploadDocumentAssets(docId, files);
    if (f.json) return printJson(res);
    out(`uploaded ${files.length} asset${files.length === 1 ? '' : 's'} to doc ${docId}`);
    return;
  }

  throw new Error(`unknown assets subcommand: ${sub}`);
}

async function cmdFolderAssets(rest) {
  const sub = rest[0];
  if (!sub) throw new Error('folder-assets requires a subcommand: list | upload | rm');
  const subRest = rest.slice(1);

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const folderId = f._[0];
    if (!folderId) throw new Error('folder-assets list requires <folder-id>');
    const { api } = buildContext(f);
    const res = await api.listFolderAssets(folderId);
    if (f.json) return printJson(res);
    const list = res.data || res.assets || res || [];
    if (!list.length) { out('(no assets)'); return; }
    for (const a of list) {
      const name = a.filename || a.name || a;
      const size = a.size ? `  ${a.size}B` : '';
      out(`${name}${size}`);
    }
    return;
  }

  if (sub === 'upload') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const folderId = f._[0];
    const files = f._.slice(1);
    if (!folderId || !files.length) throw new Error('folder-assets upload requires <folder-id> <file> [<file>...]');
    for (const fp of files) {
      if (!fs.existsSync(fp)) throw new Error(`file not found: ${fp}`);
    }
    const { api } = buildContext(f);
    const res = await api.uploadFolderAssets(folderId, files);
    if (f.json) return printJson(res);
    out(`uploaded ${files.length} asset${files.length === 1 ? '' : 's'} to folder ${folderId}`);
    return;
  }

  if (sub === 'rm' || sub === 'delete') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const folderId = f._[0];
    const filename = f._[1];
    if (!folderId || !filename) throw new Error('folder-assets rm requires <folder-id> <filename>');
    const { api } = buildContext(f);
    await api.deleteFolderAsset(folderId, filename);
    out(`deleted ${filename}`);
    return;
  }

  throw new Error(`unknown folder-assets subcommand: ${sub}`);
}

// ── Admin (requires session JWT) ─────────────────────────────────────────────

async function getAdminJwt(flags) {
  const cfg = loadConfig({ envFile: flags['env-file'], profile: flags.profile });
  const baseUrl = normalizeBaseUrl(flags.url || cfg.baseUrl);
  let username = flags.username || cfg.savedUsername;
  let password = flags.password;
  if (cfg.profileName && !password) {
    const profile = profileMod.readProfile(cfg.profileName);
    if (profile && profile.password) password = profile.password;
  }
  if (!username) username = (await promptLine('Username: ')).trim();
  if (!password) password = await promptHidden('Password: ');
  const api = buildClient({ token: '__placeholder__', baseUrl });
  const res = await api.loginPassword(username, password);
  if (!res.token) throw new Error('login response missing token');
  return { jwt: res.token, baseUrl, username };
}

async function cmdAdmin(rest) {
  const sub = rest[0];
  const sub2 = rest[1];
  if (!sub) throw new Error('admin requires a subcommand: users | settings');
  const subRest = rest.slice(2);

  if (sub === 'users') {
    if (sub2 === 'list') {
      const f = parseArgs(subRest, { boolFlags: ['json'] });
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      const res = await api.listUsers(jwt);
      if (f.json) return printJson(res);
      const list = Array.isArray(res) ? res : (res.data || []);
      if (!list.length) { out('(no users)'); return; }
      for (const u of list) out(`${u.username.padEnd(24)}  ${u.role}  ${u.created_at || ''}`);
      return;
    }
    if (sub2 === 'add' || sub2 === 'create') {
      const f = parseArgs(subRest, { boolFlags: ['json'] });
      const name = f._[0];
      if (!name) throw new Error('admin users add requires <name>');
      let password = f['new-password'] || f.password;
      if (!password) password = await promptHidden(`Password for ${name}: `);
      const role = f.role || 'viewer';
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      const res = await api.createUser(jwt, { username: name, password, role });
      if (f.json) return printJson(res);
      out(`created ${res.username}  (${res.role})`);
      return;
    }
    if (sub2 === 'update') {
      const f = parseArgs(subRest, { boolFlags: ['json'] });
      const name = f._[0];
      if (!name) throw new Error('admin users update requires <name>');
      const body = {};
      if (f.role !== undefined) body.role = f.role;
      if (f['new-password']) body.password = f['new-password'];
      if (!Object.keys(body).length) throw new Error('nothing to update (pass --role and/or --new-password)');
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      const res = await api.updateUser(jwt, name, body);
      if (f.json) return printJson(res);
      out(`updated ${res.username}  (${res.role})`);
      return;
    }
    if (sub2 === 'rm' || sub2 === 'delete') {
      const f = parseArgs(subRest, { boolFlags: ['json', 'yes'], aliases: { y: 'yes' } });
      const name = f._[0];
      if (!name) throw new Error('admin users rm requires <name>');
      if (!f.yes && process.stdin.isTTY) {
        const ok = (await promptLine(`Delete user ${name}? (y/N) `)).trim().toLowerCase();
        if (ok !== 'y' && ok !== 'yes') { out('aborted'); return; }
      }
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      await api.deleteUser(jwt, name);
      out(`deleted ${name}`);
      return;
    }
    throw new Error(`unknown admin users subcommand: ${sub2}`);
  }

  if (sub === 'settings') {
    if (sub2 === 'get') {
      const f = parseArgs(subRest, { boolFlags: ['json'] });
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      const res = await api.getSettings(jwt);
      if (f.json) return printJson(res);
      for (const [k, v] of Object.entries(res)) out(`${k}: ${v}`);
      return;
    }
    if (sub2 === 'set') {
      const f = parseArgs(subRest, { boolFlags: ['json'] });
      const body = {};
      if (f.registration !== undefined) {
        const v = String(f.registration).toLowerCase();
        body.registration_enabled = (v === 'on' || v === 'true' || v === '1');
      }
      if (!Object.keys(body).length) throw new Error('nothing to set (pass --registration on|off)');
      const { jwt, baseUrl } = await getAdminJwt(f);
      const api = buildClient({ token: '__placeholder__', baseUrl });
      const res = await api.updateSettings(jwt, body);
      if (f.json) return printJson(res);
      for (const [k, v] of Object.entries(res)) out(`${k}: ${v}`);
      return;
    }
    throw new Error(`unknown admin settings subcommand: ${sub2}`);
  }

  throw new Error(`unknown admin subcommand: ${sub}`);
}

// ── whoami / login / logout / use / profiles ─────────────────────────────────

async function cmdWhoami(rest) {
  const f = parseArgs(rest, { boolFlags: ['json'] });
  const { cfg } = buildContext(f);
  const allProfiles = profileMod.listProfiles();
  const current = profileMod.getCurrent();

  // Optionally probe /auth/me to confirm identity (best-effort)
  // Only when the token actually authenticates — agent tokens use a different
  // header so /auth/me may return 401; that's fine, we skip silently.

  if (f.json) {
    return printJson({
      active_profile: current || null,
      profile_in_use: cfg.profileName || null,
      profile_source: cfg.profileSource,
      base_url: cfg.baseUrl,
      env_file: cfg.envFilePath || null,
      token_source: cfg.tokenSource,
      token_prefix: cfg.token ? cfg.token.slice(0, 8) + '…' : null,
      username: cfg.savedUsername || null,
      token_name: cfg.savedTokenName || null,
      profiles: allProfiles.map(name => {
        const p = profileMod.readProfile(name) || {};
        return {
          name,
          base_url: p.baseUrl || null,
          username: p.username || null,
          active: name === current
        };
      })
    });
  }

  out(`active:     ${current || '(none)'}`);
  if (cfg.profileName && cfg.profileName !== current) {
    out(`in use:     ${cfg.profileName} (via ${cfg.profileSource})`);
  }
  out(`base url:   ${cfg.baseUrl}`);
  out(`env file:   ${cfg.envFilePath || '(none found)'}`);
  out(`token src:  ${cfg.tokenSource || 'none'}`);
  out(`token:      ${cfg.token ? cfg.token.slice(0, 8) + '…' : '(not set)'}`);
  if (cfg.savedUsername) out(`username:   ${cfg.savedUsername}`);
  if (cfg.savedTokenName) out(`token name: ${cfg.savedTokenName}`);
  if (allProfiles.length) {
    out('profiles:');
    for (const name of allProfiles) {
      const p = profileMod.readProfile(name) || {};
      const tag = name === current ? '  (active)' : '';
      out(`  ${name.padEnd(16)}${(p.baseUrl || '').padEnd(40)}${tag}`);
    }
  } else {
    out('profiles:   (none — run `md_cli login` to create one)');
  }
}

function warnIfShadowed(cfgPre) {
  if (process.env.MD_BROWSE_TOKEN) {
    err(
      `\nwarning: MD_BROWSE_TOKEN is set in your shell environment — it takes priority\n`
      + `         over the saved token. Unset it (\`unset MD_BROWSE_TOKEN\`) or the\n`
      + `         saved token won't be used.`
    );
  } else if (cfgPre.tokenSource === 'env-file' && cfgPre.envFilePath) {
    err(
      `\nwarning: MD_BROWSE_TOKEN is set in ${cfgPre.envFilePath} — it takes priority\n`
      + `         over the saved token. Remove it from .env or the saved token\n`
      + `         won't be used. Run \`md_cli whoami\` to see which is active.`
    );
  }
}

const DEFAULT_TOKEN_SCOPES = [
  'documents:read', 'documents:write', 'versions:read', 'search:read', 'audit:read'
];

function resolveLoginProfile(flags, baseUrl) {
  const explicit = !!flags.profile;
  let name = flags.profile || profileMod.deriveName(baseUrl);
  profileMod.validateName(name);
  return { name, exists: profileMod.profileExists(name), explicit };
}

async function cmdLogin(rest) {
  const f = parseArgs(rest, { boolFlags: ['no-validate', 'no-switch', 'force', 'save-password'] });
  const cfgPre = loadConfig({ envFile: f['env-file'] });
  const baseUrl = normalizeBaseUrl(f.url || cfgPre.baseUrl);
  if (!baseUrl) throw new Error('login requires --url or MD_BROWSE_URL set in your environment');

  const { name: profileName, exists: profileExists, explicit: profileExplicit } =
    resolveLoginProfile(f, baseUrl);

  if (profileExists && !profileExplicit && !f.force) {
    throw new Error(
      `profile "${profileName}" already exists. ` +
      `Use --profile <new-name> to pick a different name, ` +
      `or --force to overwrite (the old token will no longer be remembered).`
    );
  }

  // Path 1: --token escape hatch.
  if (f.token) {
    const token = f.token;
    if (!f['no-validate']) {
      const api = buildClient({ token, baseUrl });
      try { await api.listDocuments({ page_size: 1 }); }
      catch (e) {
        const msg = e instanceof ApiError ? `${e.message} (HTTP ${e.status})` : (e.message || String(e));
        throw new Error(`token validation failed: ${msg}`);
      }
    }
    profileMod.writeProfile(profileName, {
      token, baseUrl, saved_at: new Date().toISOString()
    });
    if (!f['no-switch']) profileMod.setCurrent(profileName);
    out(`saved to  ${profileMod.profilePath(profileName)}`);
    out(`profile:  ${profileName}${f['no-switch'] ? '' : '  (active)'}`);
    out(`base url: ${baseUrl}`);
    out(`token:    ${token.slice(0, 8)}…`);
    warnIfShadowed(cfgPre);
    return;
  }

  // Path 2 (default): username/password → mint a long-lived agent token.
  let username = f.username || f.user;
  if (!username) username = (await promptLine('Username: ')).trim();
  if (!username) throw new Error('login requires a username');

  const password = f.password !== undefined ? f.password : await promptHidden('Password: ');
  if (!password) throw new Error('password is required');

  const api = buildClient({ token: '__placeholder__', baseUrl });
  let session;
  try {
    session = await api.loginPassword(username, password);
  } catch (e) {
    if (e instanceof ApiError) throw new Error(`login failed (HTTP ${e.status}): ${e.body?.error?.message || 'check username/password'}`);
    throw new Error(`could not reach ${baseUrl}/api/auth/login: ${e.message}`);
  }
  const jwt = session.token;
  if (!jwt) throw new Error('login response missing token');

  const tokenName = f.name || `md_cli@${os.hostname()} ${new Date().toISOString().slice(0, 16).replace('T', ' ')}`;
  const scopes = f.scopes
    ? String(f.scopes).split(',').map(s => s.trim()).filter(Boolean)
    : DEFAULT_TOKEN_SCOPES;

  let minted;
  try {
    minted = await api.mintAgentToken(jwt, { name: tokenName, scopes });
  } catch (e) {
    if (e instanceof ApiError) {
      throw new Error(`failed to mint token (HTTP ${e.status}): ${e.body?.error?.message || ''}`);
    }
    throw e;
  }
  const secretToken = minted.secret_token;
  if (!secretToken) throw new Error('token creation response missing secret_token');

  const state = {
    token: secretToken,
    baseUrl,
    username,
    token_name: tokenName,
    saved_at: new Date().toISOString()
  };
  if (f['save-password']) state.password = password;
  profileMod.writeProfile(profileName, state);
  if (!f['no-switch']) profileMod.setCurrent(profileName);
  out(`logged in as ${username}`);
  out(`saved to  ${profileMod.profilePath(profileName)}`);
  out(`profile:  ${profileName}${f['no-switch'] ? '' : '  (active)'}`);
  out(`base url: ${baseUrl}`);
  out(`token:    ${secretToken.slice(0, 8)}…  (name: ${tokenName})`);
  out(`scopes:   ${scopes.join(', ')}`);
  if (f['save-password']) out(`note:     password stored in profile (admin commands won't re-prompt)`);
  warnIfShadowed(cfgPre);
}

async function cmdLogout(rest) {
  const f = parseArgs(rest, { boolFlags: ['all'] });
  if (f.all) {
    const all = profileMod.listProfiles();
    if (!all.length) { out('no profiles to remove'); return; }
    for (const name of all) profileMod.deleteProfile(name);
    profileMod.clearCurrent();
    out(`removed ${all.length} profile${all.length === 1 ? '' : 's'}: ${all.join(', ')}`);
    return;
  }
  const target = f.profile || profileMod.getCurrent();
  if (!target) {
    out('no active profile to log out of. Use `md_cli profiles rm <name>` to delete a specific profile.');
    return;
  }
  const removed = profileMod.deleteProfile(target);
  if (target === profileMod.getCurrent()) profileMod.clearCurrent();
  out(removed ? `removed profile: ${target}` : `profile not found: ${target}`);
  if (removed && !profileMod.getCurrent()) {
    const remaining = profileMod.listProfiles();
    if (remaining.length) {
      profileMod.setCurrent(remaining[0]);
      out(`active profile is now: ${remaining[0]}`);
    }
  }
}

async function cmdUse(rest) {
  const f = parseArgs(rest);
  const name = f._[0];
  if (!name) throw new Error('use requires a profile name. Try `md_cli profiles` to list available profiles.');
  profileMod.validateName(name);
  if (!profileMod.profileExists(name)) {
    const all = profileMod.listProfiles();
    throw new Error(
      `no such profile: ${name}.${all.length ? ` Available: ${all.join(', ')}` : ' Run `md_cli login` first.'}`
    );
  }
  profileMod.setCurrent(name);
  const p = profileMod.readProfile(name) || {};
  out(`active profile: ${name}${p.baseUrl ? `  (${p.baseUrl})` : ''}`);
}

async function cmdProfiles(rest) {
  const sub = rest[0] && !rest[0].startsWith('-') ? rest[0] : 'list';
  const subRest = (sub === rest[0]) ? rest.slice(1) : rest;

  if (sub === 'list') {
    const f = parseArgs(subRest, { boolFlags: ['json'] });
    const all = profileMod.listProfiles();
    const current = profileMod.getCurrent();
    if (f.json) {
      return printJson({
        active: current || null,
        profiles: all.map(name => {
          const p = profileMod.readProfile(name) || {};
          return { name, base_url: p.baseUrl || null, username: p.username || null, active: name === current };
        })
      });
    }
    if (!all.length) { out('(no profiles — run `md_cli login` to create one)'); return; }
    for (const name of all) {
      const p = profileMod.readProfile(name) || {};
      const tag = name === current ? '  (active)' : '';
      out(`${name.padEnd(16)}${(p.baseUrl || '').padEnd(40)}${tag}`);
    }
    return;
  }

  if (sub === 'rm' || sub === 'delete' || sub === 'remove') {
    const f = parseArgs(subRest);
    const name = f._[0];
    if (!name) throw new Error('profiles rm requires a name');
    profileMod.validateName(name);
    if (!profileMod.profileExists(name)) throw new Error(`no such profile: ${name}`);
    profileMod.deleteProfile(name);
    if (profileMod.getCurrent() === name) profileMod.clearCurrent();
    out(`removed profile: ${name}`);
    return;
  }

  if (sub === 'rename' || sub === 'mv') {
    const f = parseArgs(subRest);
    const oldName = f._[0];
    const newName = f._[1];
    if (!oldName || !newName) throw new Error('profiles rename requires <old> <new>');
    profileMod.validateName(oldName);
    profileMod.validateName(newName);
    if (!profileMod.profileExists(oldName)) throw new Error(`no such profile: ${oldName}`);
    if (profileMod.profileExists(newName)) throw new Error(`profile already exists: ${newName}`);
    const data = profileMod.readProfile(oldName);
    profileMod.writeProfile(newName, data);
    profileMod.deleteProfile(oldName);
    if (profileMod.getCurrent() === oldName) profileMod.setCurrent(newName);
    out(`renamed ${oldName} → ${newName}`);
    return;
  }

  throw new Error(`unknown profiles subcommand: ${sub}\nrun \`md_cli help profiles\` for usage.`);
}

// ── Dispatch ─────────────────────────────────────────────────────────────────

const COMMANDS = {
  list: cmdList,
  ls: cmdList,
  search: cmdSearch,
  get: cmdGet,
  upload: cmdUpload,
  update: cmdUpdate,
  delete: cmdDelete,
  rm: cmdDelete,
  versions: cmdVersions,
  rollback: cmdRollback,
  chunks: cmdChunks,
  download: cmdDownload,
  'download-batch': cmdDownloadBatch,
  'batch-delete': cmdBatchDelete,
  'batch-move': cmdBatchMove,
  share: cmdShare,
  folders: cmdFolders,
  folder: cmdFolders,
  tokens: cmdTokens,
  audit: cmdAudit,
  'audit-logs': cmdAudit,
  categories: cmdCategories,
  tags: cmdTags,
  health: cmdHealth,
  ping: cmdHealth,
  assets: cmdAssets,
  'folder-assets': cmdFolderAssets,
  admin: cmdAdmin,
  login: cmdLogin,
  logout: cmdLogout,
  whoami: cmdWhoami,
  use: cmdUse,
  profiles: cmdProfiles,
  profile: cmdProfiles
};

// Global flags accepted before the command; lifted out and appended to the
// command's own argv so `md_cli --url X list` and `md_cli list --url X` behave
// identically.
const GLOBAL_VALUE_FLAGS = new Set(['--token', '--url', '--env-file', '--profile']);
const GLOBAL_BOOL_FLAGS = new Set(['--json']);

function liftGlobalFlags(argv) {
  const lifted = [];
  let i = 0;
  while (i < argv.length) {
    const a = argv[i];
    if (a === '--') break;
    if (GLOBAL_BOOL_FLAGS.has(a)) { lifted.push(a); i += 1; continue; }
    const eq = a.indexOf('=');
    const head = eq >= 0 ? a.slice(0, eq) : a;
    if (GLOBAL_VALUE_FLAGS.has(head)) {
      if (eq >= 0) { lifted.push(a); i += 1; }
      else { lifted.push(a, argv[i + 1]); i += 2; }
      continue;
    }
    break;
  }
  return { lifted, rest: argv.slice(i) };
}

async function run(rawArgv) {
  const { lifted, rest: argv } = liftGlobalFlags(rawArgv);

  if (!rawArgv.length) {
    out(HELP);
    out(ABOUT);
    return;
  }
  if (!argv.length || argv[0] === '-h' || argv[0] === '--help' || argv[0] === 'help') {
    if (argv[1] && COMMAND_HELP[argv[1]]) {
      out(COMMAND_HELP[argv[1]]);
    } else {
      out(HELP);
    }
    return;
  }
  if (argv[0] === '--version' || argv[0] === '-v' || argv[0] === 'version') {
    out(`md_cli ${VERSION}  ·  build ${BUILD}`);
    return;
  }

  const [cmd, ...subArgv] = argv;
  const rest = subArgv.concat(lifted);
  const handler = COMMANDS[cmd];
  if (!handler) {
    throw new Error(`unknown command: ${cmd}\nrun \`md_cli help\` for usage.`);
  }

  if (rest.includes('-h') || rest.includes('--help')) {
    out(COMMAND_HELP[cmd] || HELP);
    return;
  }

  try {
    await handler(rest);
  } catch (e) {
    if (e instanceof ApiError) {
      const reqId = e.requestId ? ` (request_id=${e.requestId})` : '';
      throw new Error(`${e.message}${reqId}`);
    }
    throw e;
  }
}

module.exports = { run };
